### ISSUE TITLE
Saving 'z_local' queastion

### ISSUE THREAD

**Issue by A474852023** [dodaltuin/passive-lv-gnn-emul#1] opened 2024-05-20 01:56 UTC
Dear David:
I want to save the z_local variable to a file. I tried to change the 'sow_latents' of the '__call__' function in the 'DeepGraphEmulator' class of file ‘models.py‘ to 'True' after completing the training. Please check the following code.
Thank you very much!
Yours
      Siyuan,Lv and Zheng,Duanmu 

The following is my saving code:
```python
# Here I have changed : sow_latents: bool = True
def __call__(self, V: jnp.ndarray, E: jnp.ndarray, theta: jnp.ndarray, z_global: jnp.ndarray = None, sow_latents: bool = True):
……….
# only need local representation for real nodes
z_local = z_local[self.real_node_indices]

# Here is my saving z_local code
z_local_np = np.array(z_local)
np.save('z_local_1.npy', z_local_np)

# save value of final learned representation if required for fixed geometry emulator
if sow_latents:
    return z_local
```

**Comment by dodaltuin** [comment] 2024-05-23 17:25
Hi there,

Apologies for the delay in response, I have had a busy week. 

I'm afraid your code won't work inside a jitted function - see the discussion [here](https://github.com/google/jax/discussions/3766) for more details. There are two workarounds - don't jit the function when you call it, or else return z_local from the function call and then save.

Also, one thing to mention - this concept of not including the material parameters inside the message passing stage - I only did this to get faster prediction times after training. You will get more accurate results if the material parameters are included in the message passing (by just appending them to the node features).

David

**Comment by A474852023** [comment] 2024-05-25 03:25
Dear David:
I apologize for disturbing you and greatly appreciate your response. I tried my best but still got some problem.
First I tried saving 'z_local' to 'self.z_local' of the 'DeepGraphEmulator' class
```python
# only need local representation for real nodes
        z_local = z_local[self.real_node_indices]
        ############### save z_local to self.zlocal ############
        self.sow('z_local', 'latent_representation', z_local)
```
```python
    V, E, theta, z_global, _ = train_data.return_index_0()
    z_local = model.apply(state.target, V, E, theta, z_global, sow_latents=True)
    np.save(f'{results_save_dir}/z_local.npy', z_local)
```
I got a (96,80) npy file.But after reducing the data to 2 dimensions with pca, it still differs from the pca results in your article.

Then I tried to use 'host_callback', but this time i got a (21600,80) file each epoch.
```python
def save_z_local(z_local, epoch_idx, results_save_dir):
    def save_to_file(z,_):
        np.save(f'{results_save_dir}/z_local_epoch_{epoch_idx}.npy', z)
    hcb.id_tap(save_to_file, z_local)
# I returned both Upred and z_local at the end of '__call__'. So I had to change a lot of code that called 'Upred'
```
Finally, I tried to return 'z_local' directly by setting 'sow_latents' to 'True'. But this time I got an error and I just can't fix it.
```python
    V, E, theta, z_global, _ = train_data.return_index_0()
    z_local = model.apply({'params': params}, V, E, theta, z_global, save_latents=True)
    np.save('z_local.npy', np.array(z_local))  # 将z_local保存到npy文件中
```
The error was:
z_local = model.apply({'params': params}, V, E, theta, z_global, save_latents=True)
TypeError: __call__() got an unexpected keyword argument 'save_latents'

Thank you for taking the time to read my question. I look forward to your response.

Yours
Siyuan,Lv and Zheng,Duanmu

**Comment by dodaltuin** [comment] 2024-05-25 09:37
Ok, I think I see what the problem is relating to the PCA.

Firstly - the (96,80) array is for the single test geometry, which has 96 nodes. The (21600,80) array is for the entire test data of 225 simulations (225*96=21600). For doing the dimension reduction - fit the PCA on the (21600,80) array, and then use your learned PCA projection to reduce the (96,80) test array to two dimensions. 

It appears to me that you instead fit the PCA on the (96,80) test array, which is not what I did, so the results won't match.

For your final error - I'm not sure what's going on there. If you could first let me know if the above helps you with the PCA errors, that would be great.

**Comment by dodaltuin** [comment] 2024-05-25 10:01
Ok so I went back to my workings on this and actually I did the PCA a little bit differently (apologies it's been a while since I did this work).

In any case, I fit the PCA on the dataset of latent vectors from the validation set - this data can be downloaded here: 
[pca_train_array.zip](https://github.com/dodaltuin/passive-lv-gnn-emul/files/15442584/pca_train_array.zip).

**Comment by A474852023** [comment] 2024-05-25 11:29
Thank you very much for your guidance. I can get the right results now.
Thanks again!

**Comment by dodaltuin** [comment] 2024-05-25 11:42
No problem at all. 

I will close this issue for now - feel free to open another one if you run in to any more problems.

Thanks,
David

**Closed as completed by dodaltuin** 2024-05-25 11:42 UTC
